FROM tensorflow/tensorflow:2.1.0-gpu-py3-jupyter
RUN python3 -m pip install --no-cache-dir --upgrade pip
RUN python3 -m pip install --no-cache-dir pandas
RUN python3 -m pip install --no-cache-dir tensorflow-datasets
